apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: cert-manager
  releaseName: cert-manager
  version: v1.14.2
  namespace: cert-manager
  repo:  https://charts.jetstack.io
  valuesInline:
    installCRDs: true
    nodeSelector:
      cloud.google.com/gke-spot: "true"
      kubernetes.io/os: linux
    webhook:
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-spot: "true"
    cainjector:
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-spot: "true"
    startupapicheck:
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-spot: "true"
