apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ingress-nginx
  includeCRDs: false
  releaseName: ingress-nginx
  version: 4.9.1
  namespace: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  valuesInline:
    controller:
      replicaCount: 2
      autoscaling:
        enabled: true
        minReplicas: 2
      nodeSelector:
        cloud.google.com/gke-spot: "true"
        kubernetes.io/os: linux
    admissionWebhooks:
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-spot: "true"
    defaultBackend:
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-spot: "true"
