---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove Trailing Whitespaces
      - id: end-of-file-fixer
        name: Fix End-Of-File Endings
      - id: check-yaml
        name: Check YAML
      - id: check-added-large-files
        name: Check For Large Files
      - id: detect-private-key
        name: Detect Private Keys
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
        name: Terragrunt FMT
      - id: tflint
        files: ^infrastructure/
        name: TFLint
      - id: terraform-validate
        files: ^infrastructure/
        name: Terraform Validate
