apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: external-secrets
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    repo: https://charts.external-secrets.io
    chart: external-secrets
    version: 9.3.1
    releaseName: external-secrets
    namespace: external-secrets
    values:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
        kubernetes.io/os: linux
